# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180714_2308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
